### ISSUE TITLE
" equivalence_properties_query.sparql " file is missing

### ISSUE THREAD

**Issue by parthrohilla** [sgottsch/eventkg#2]
Hello,
While implementing STEP-1 ,the following file which downloads the WIKIDATA DUMPS seems to be missing:
 **/resource/meta_data/wikidata/equivalence_properties_query.sparql**
There is no such file in the assigned location.The error message shown is->

path_to_config_file.txt 1
Step 1: Download files.
Copy meta files.
Exception in thread "main" java.lang.NullPointerException
	at de.l3s.eventkg.pipeline.RawDataDownLoader.downloadWikidataQueryFiles(RawDataDownLoader.java:297)
	at de.l3s.eventkg.pipeline.RawDataDownLoader.downloadWikidataFile(RawDataDownLoader.java:269)
	at de.l3s.eventkg.pipeline.RawDataDownLoader.downloadFiles(RawDataDownLoader.java:195)
	at de.l3s.eventkg.pipeline.Pipeline.download(Pipeline.java:118)
	at de.l3s.eventkg.pipeline.Pipeline.main(Pipeline.java:71)

**Comment by sgottsch** [comment]
Hello,
I have just committed the missing file to the repo.
